sql_query_customer_table = '''CREATE TABLE CUSTOMER_INFO(
   ID INT PRIMARY KEY AUTO_INCREMENT,
   USER_NAME VARCHAR(30) NOT NULL,
   AGE INT,
   SEX CHAR(1),
   PASSWORD VARCHAR(255),
   EMAIL VARCHAR(50)
)
'''

sql_query_training_table = '''CREATE TABLE CUSTOMER_TRAINING_INFO(
   ID INT,
   TRAINING_DATE DATE,
   EXERCISES  TEXT,
   FOREIGN KEY (ID) REFERENCES CUSTOMER_INFO(ID)
)
'''

sql_query_diet_table = '''CREATE TABLE CUSTOMER_DIET_INFO(
   ID INT,
   REPORTED_DATE DATE,
   BREAKFAST  VARCHAR(255),
   SNACK_1 VARCHAR(255),
   LUNCH VARCHAR(255),
   SNACK_2 VARCHAR(255),
   DINNER VARCHAR(255),
   SNACK_3 VARCHAR(255),
   SCORE INT,
   FOREIGN KEY (ID) REFERENCES CUSTOMER_INFO(ID)
)
'''

